<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('css/style.css'))
    ?>

    <!-- Scripts -->
    <?php
    $this->inlineScript()
        ->appendFile($this->basePath('js/jquery-3.5.1.min.js'))
        ->appendFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile($this->basePath('js/app.js'))
    ?>
</head>

<body>
    <header id="header">
        <nav>
            <div class="header-logo">
                <img class="logo" src="images/archeryZone-removebg-preview.png" />
            </div>
            <ul>
                <li><a href="#range">range</a></li>
                <li><a href="#tag">archery tag</a></li>
                <li><a href="/pricing">pricing</a></li>
                <li><a href="<?=$this->url('app', ['action' => 'contact'])?>">contact</a></li>
                <li class="filled-btn"><a class="button " href="#">book now</a></li>
            </ul>

            <div class="mobile-menu-icon">
                <div class="hamburger-menu">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <div class="footer-container">
                <div class="footer-logo">
                    <img width="150px" src="images/archeryZone-removebg-preview.png" alt="" />
                </div>
                <p>&copy 2022 All Rights Reserved</p>
            </div>
        </footer>
    </div>

    <?= $this->inlineScript() ?>

</body>

</html>