<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Archery Zone')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?php
        $this->inlineScript()
            ->appendFile($this->basePath('js/jquery-3.5.1.min.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/app.js'))
        ?>
    </head>
    <body class="bg-dark text-white">
        <main class="container wrapper fill bg-light rounded-top rounded-bottom" role="main">
            <div class="row">
                <div class="col-2 align-self-end">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/header.png') ?>" alt="Archery Zone">
                    </a>
                </div>
                <div class="col-8 align-self-start">
                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <div id="main-navigation" class="mx-auto">
                                <a role="button" class="btn btn-outline-light<?=$this->action === 'index' ? ' active' : ''?>" href="<?= $this->url('home') ?>">
                                Home <?=$this->action === 'index' ? '<span class="sr-only">(current)</span>' : ''?>
                                </a>
                                <a role="button" class="btn btn-outline-light<?=$this->action === 'range' ? ' active' : ''?>" href="<?= $this->url('app', ['action' => 'range']) ?>">
                                Range <?=$this->action === 'range' ? '<span class="sr-only">(current)</span>' : ''?>
                                </a>
                                <a role="button" class="btn btn-outline-light<?=$this->action === 'archery-tag' ? ' active' : ''?>" href="<?= $this->url('app', ['action' => 'archery-tag']) ?>">
                                Archery Tag <?=$this->action === 'archery-tag' ? '<span class="sr-only">(current)</span>' : ''?>
                                </a>
                                <a role="button" class="btn btn-outline-light<?=$this->action === 'pricing' ? ' active' : ''?>" href="<?= $this->url('app', ['action' => 'pricing']) ?>">
                                Pricing <?=$this->action === 'pricing' ? '<span class="sr-only">(current)</span>' : ''?>
                                </a>
                                <a role="button" class="btn btn-outline-light<?=$this->action === 'contact' ? ' active' : ''?>" href="<?= $this->url('app', ['action' => 'contact']) ?>">
                                Contact <?=$this->action === 'contact' ? '<span class="sr-only">(current)</span>' : ''?>
                                </a>
                                <a role="button" class="btn btn-outline-light<?=$this->action === 'book-now' ? ' active' : ''?>" href="<?= $this->url('app', ['action' => 'book-now']) ?>">
                                Book Now <?=$this->action === 'book-now' ? '<span class="sr-only">(current)</span>' : ''?>
                                </a>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            <div id="app-workspace" class="container">
                <?= $this->content ?>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-3 mx-auto">
                        <footer>
                            <div class="footer-container">
                                <p>&copy; <?= date('Y') ?> All Rights Reserved</p>
                            </div>
                        </footer>
                    </div>
                </div>
            </div>
        </main>
        <?= $this->inlineScript() ?>
    </body>
</html>