<?php

declare(strict_types=1);
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
?>
<!-- ARCHERY TAG SECTION -->
<section id="tag">
    <div class="tag-container">
        <div class="tag-left-container">
            <!-- TAG ABOUT -->
            <div class="tag-about">
                <h2>ARCHERY TAG!</h2>
                <h4>Reservations Required</h4>
                <p>
                    Similar to paintball, eliminate your opponents and score points to
                    win in this 15 minute fast paced game, where shooting your
                    friends, family and strangers with a foam tipped arrow is
                    encouraged.
                </p>
            </div>
            <div class="tag-cards">
                <!-- CARD 2 -->
                <div class="range-card">
                    <div class="range-icon">
                        <i class="fa-solid fa-medal"></i>
                    </div>
                    <div class="range-card-content">
                        <h3>
                            <span class="bold">30/GEL per 1 person PER 1 HOUR </span>
                        </h3>
                        <p>Contact us to book additional time beyond an hour</p>
                    </div>
                </div>
                <!-- CARD 3 -->
                <div class="range-card">
                    <div class="range-icon">
                        <i class="fa-solid fa-people-group"></i>
                    </div>
                    <div class="range-card-content">
                        <h3>
                            <span class="bold">UP TO 20 PLAYERS PER GAME (Up To 10 VS 10)</span>
                        </h3>
                        <p>
                            Nothing beats shooting your first 10. Learn how to be an archer
                            but have fun doing it!
                        </p>
                    </div>
                </div>
                <!-- CARD 4 -->
                <div class="range-card">
                    <div class="range-icon">
                        <i class="fa-solid fa-cake-candles"></i>
                    </div>
                    <div class="range-card-content">
                        <h3><span class="bold">BIRTHDAYS & TEAM BUILDING</span></h3>
                        <p>
                            This is an awesome yet unique game for events or birthdays,
                            contact us for a reservation.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- TAG RIGHT -->
        <div class="tag-right-container">
            <div class="tag-img">
                <img src="./images/tag.jpg" alt="">
            </div>
            <div class="tag-img">
                <img src="./images/tag2.jpg" alt="">
            </div>
        </div>
    </div>
</section>