<?php

declare(strict_types=1);
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
?>

<!-- HOME SECTION -->
<section id="home">
    <div class="row">
        <div class="col-10 mx-auto">
            <div class="card bg-secondary">
                <div class="card-header border-bottom-0">
                    <h2>Archery</h2>
                </div>
                <div class="card-body">
                    <h3>400sqft TBILISI Archery Range</h3>
                    <p>Load your bow, take aim and let the arrow fly</p>
                </div>
            </div>
        </div>
    </div>
</section>
