<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<!--  BOOK NOW POPUP -->
<div class="popup">
    <div class="popup-content">

        <i class="fa-solid fa-xmark close" id="close"></i>


        <div class="main-popup">

            <form method="get">
                <div>
                    <label for="name">Your Full Name</label>
                    <input type="text" name="name" placeholder="Write Your Name" required />
                </div>
                <div>
                    <label for="name">Your Email Adress</label>
                    <input type="text" name="name" placeholder="Write Your Email" required />
                </div>
                <div>
                    <label for="name">How Many Lane?</label>
                    <select name="people" id="people">
                        <option value="">---Lane---</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>

                </div>
                <div>
                    <label for="time">What Time?</label>
                    <select name="time" id="time">
                        <option value="">---Time---</option>

                        <option value="2">12PM</option>
                        <option value="3">1PM</option>
                        <option value="4">2PM</option>
                        <option value="5">3PM</option>
                        <option value="5">4PM</option>
                        <option value="5">5PM</option>
                        <option value="5">6PM</option>
                        <option value="5">7PM</option>
                        <option value="5">8PM</option>
                    </select>
                </div>
                <div>
                    <label for="date">What Is The Date?</label>
                    <input id="date" type="date" name="date" placeholder="Date" required />
                </div>
                <div>
                    <label for="name">Your Phone Number</label>
                    <input id="number" type="text" name="number" placeholder="Write Your Number Here" required />
                </div>

        </div>
        <div class="submit">
            <input type="submit" name="submit" value="BOOK NOW" id="submit" />
        </div>
        </form>
    </div>
</div>
</div>
<!-- END OF POPUP -->

<!-- HOME SECTION -->
<main>
    <section id="home">
        <div class="home-container">
            <div class="home-card-container">
                <div class="home-card">
                    <div class="card-content">
                        <h2>Archery</h2>
                        <h3>400sqft TBILISI Archery Range</h3>
                        <p>Load your bow, take aim and let the arrow fly</p>
                        <button class="button filled-btn">Book Now</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- RANGE SECTION -->
    <section id="range">
        <div class="range-container">
            <div class="range-top-content">
                <h2>OUR RANGE</h2>
                <p>
                    Premier archery range in Tblisi.
                    <span class="bold">New to archery? We are here to help.</span>
                    Watch a short <a target="_blank" href="https://www.youtube.com/watch?v=BfIRIFSe4aw">introductory video found here</a> on
                    archery, and our professionals on the range will help reinforce what
                    you learn
                </p>
            </div>

            <div class="range-content">
                <div class="range-left-content">
                    <!-- card 1 -->
                    <div class="range-card">
                        <div class="range-icon"><i class="fa-regular fa-star"></i></div>
                        <div class="range-card-content">
                            <h3><span class="bold">5-20 Meters RANGE </span></h3>
                            <p>
                                Start out shooting at 10 Meters if you'd like! Our range can
                                accommodate <span class="bold">all skill levels.</span>
                            </p>
                        </div>
                    </div>
                    <!-- card 2 -->
                    <div class="range-card">
                        <div class="range-icon">
                            <i class="fa-solid fa-crosshairs"></i>
                        </div>
                        <div class="range-card-content">
                            <h3> <span class="bold">FAMILY FRIENDLY: AGE 10+</span></h3>
                            <p>
                                Bring the whole family! A great way to spend your evenings or
                                afternoons with us at Archery
                            </p>
                        </div>
                    </div>
                    <!-- card 3 -->
                    <div class="range-card">
                        <div class="range-icon">
                            <i class="fa-sharp fa-solid fa-credit-card"></i>
                        </div>
                        <div class="range-card-content">
                            <h3>
                                <span class="bold"> ONLY 30 GEL/HOUR</span>
                                <span class="bold">EQUIPMENT PROVIDED</span>
                            </h3>
                            <p>
                                No need to own equipment. Impact Archery will provide you with
                                the equipment and instruction.
                            </p>
                        </div>
                    </div>
                    <div class="range-card">
                        <div class="range-icon">
                            <i class="fa-solid fa-certificate"></i>
                        </div>
                        <div class="range-card-content">
                            <h3><span class="bold">PROFESSIONAL HELP</span></h3>
                            <p>
                                Our certified professionals will assist you while you shoot.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="range-right-content">
                    <div class="slide-container">
                        <div class="images-container">
                            <img class="img-slide" src="./images/img2.jpg" alt="" />
                            <img class="img-slide" src="./images/img3.jpg" alt="" />
                            <img class="img-slide" src="./images/img1.jpg" alt="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ARCHERY TAG SECTION -->
    <section id="tag">
        <div class="tag-container">
            <div class="tag-left-container">
                <!-- TAG ABOUT -->
                <div class="tag-about">
                    <h2>ARCHERY TAG!</h2>
                    <h4>Reservations Required</h4>
                    <p>
                        Similar to paintball, eliminate your opponents and score points to
                        win in this 15 minute fast paced game, where shooting your
                        friends, family and strangers with a foam tipped arrow is
                        encouraged.
                    </p>
                </div>

                <div class="tag-cards">
                    <!-- CARD 2 -->
                    <div class="range-card">
                        <div class="range-icon">
                            <i class="fa-solid fa-medal"></i>
                        </div>
                        <div class="range-card-content">
                            <h3>
                                <span class="bold">30/GEL per 1 person PER 1 HOUR </span>
                            </h3>
                            <p>Contact us to book additional time beyond an hour</p>
                        </div>
                    </div>
                    <!-- CARD 3 -->
                    <div class="range-card">
                        <div class="range-icon">
                            <i class="fa-solid fa-people-group"></i>
                        </div>
                        <div class="range-card-content">
                            <h3>
                                <span class="bold">UP TO 20 PLAYERS PER GAME (Up To 10 VS 10)</span>
                            </h3>
                            <p>
                                Nothing beats shooting your first 10. Learn how to be an archer
                                but have fun doing it!
                            </p>
                        </div>
                    </div>
                    <!-- CARD 4 -->
                    <div class="range-card">
                        <div class="range-icon">
                            <i class="fa-solid fa-cake-candles"></i>
                        </div>
                        <div class="range-card-content">
                            <h3><span class="bold">BIRTHDAYS & TEAM BUILDING</span></h3>
                            <p>
                                This is an awesome yet unique game for events or birthdays,
                                contact us for a reservation.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- TAG RIGHT -->
            <div class="tag-right-container">
                <div class="tag-img">

                    <img src="./images/tag.jpg" alt="">
                </div>
                <diiv class="tag-img">


                    <img src="./images/tag2.jpg" alt="">
                </diiv>
            </div>
        </div>
    </section>
</main>
<!-- PRICING SECTON -->
<section id="pricing">
    <div class="table-container">
        <h2>PRCING</h2>
        <table>
            <tr>
                <th>Item</th>
                <th>Quanity</th>
                <th>Pricing</th>
            </tr>
            <tr>
                <td class="bold">Range Fee</td>
                <td>1 Hour</td>
                <td>25/GEL</td>
            </tr>
            <tr>
                <td class="bold">Recurve Shooting Experience</td>
                <td>1 Hour</td>
                <td>30/GEL</td>
            </tr>
            <tr>
                <td class="bold">Private Lesson</td>
                <td>1 Hour</td>
                <td>50/GEL</td>
            </tr>
            <tr>
                <td class="bold">1 Month Membership*</td>
                <td>1 Monthr</td>
                <td>110/GEL</td>
            </tr>
            <tr>
                <td class="bold">1 Year Membership*</td>
                <td>1 Year</td>
                <td>800/GEL</td>
            </tr>
        </table>
        <div class="book-now">
            <button class="button"><a href="#">BOOK NOW</a></button>
        </div>
    </div>
</section>
<!-- CONTACT SECTION -->
<section id="contact">
    <div class="contact-container">
        <dv class="contact-info">
            <div class="contact-header">
                <h3>CONTACT US</h3>
            </div>
            <div class="contact-flex">
                <i class="fa-solid fa-phone"></i>
                <h4>+995-599-060-235</h4>
            </div>
            <div class="contact-flex">
                <i class="fa-solid fa-envelope"></i>
                <h4>annageld508@gmail.com</h4>
            </div>
            <div class="contact-flex">
                <i class="fa-solid fa-location-pin"></i>
                <h4>Tbilisi,Georgia</h4>
            </div>



        </dv>
        <div class="contact-icons">
            <ul>
                <li><i class="fa-brands fa-facebook"></i></li>
                <li><i class="fa-brands fa-instagram"></i></li>
                <li><i class="fa-brands fa-youtube"></i></li>
            </ul>
        </div>
    </div>
</section>