<?php

declare(strict_types=1);
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
?>
<div class="row">
    <div class="col-10 mx-auto">
        <div class="card bg-secondary text-center">
            <div class="card-header text-left">
                <a class="btn btn-secondary active" href="#">Book Now</a>
            </div>
            <div class="card-body">
                <div class="row pricing-table">
                    <div class="col-12 mx-auto">
                        <div class="row table-head border-bottom border-dark">
                            <div class="col-4 head-item">Item</div>
                            <div class="col-4 head-item">Quantity</div>
                            <div class="col-4 head-item">Pricing</div>
                        </div>
                        <div class="row table-row border-bottom border-dark">
                            <div class="col-4 col-item">Range Fee</div>
                            <div class="col-4 col-item">1 Hour</div>
                            <div class="col-4 col-item">25/GEL</div>
                        </div>
                        <div class="row table-row border-bottom border-dark">
                            <div class="col-4">Recurve Shooting Experience</div>
                            <div class="col-4">1 Hour</div>
                            <div class="col-4">30/GEL</div>
                        </div>
                        <div class="row table-row border-bottom border-dark">
                            <div class="col-4">Private Lesson</div>
                            <div class="col-4">1 Hour</div>
                            <div class="col-4">50/GEL</div>
                        </div>
                        <div class="row table-row border-bottom border-dark">
                            <div class="col-4">Monthly Membership</div>
                            <div class="col-4">1 Month</div>
                            <div class="col-4">110/GEL</div>
                        </div>
                        <div class="row table-row border-bottom border-dark">
                            <div class="col-4">Yearly Membership</div>
                            <div class="col-4">1 Year</div>
                            <div class="col-4">800/GEL</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

