<?php

declare(strict_types=1);
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->headTitle($this->title);
?>
<!-- RANGE SECTION -->
<section id="range">
    <div class="range-container">
        <div class="range-top-content">
            <h2>OUR RANGE</h2>
            <p>
                Premier archery range in Tblisi.
                <span class="bold">New to archery? We are here to help.</span>
                Watch a short <a target="_blank" href="https://www.youtube.com/watch?v=BfIRIFSe4aw">introductory video found here</a> on
                archery, and our professionals on the range will help reinforce what
                you learn
            </p>
        </div>

        <div class="range-content">
            <div class="range-left-content">
                <!-- card 1 -->
                <div class="range-card">
                    <div class="range-icon"><i class="fa-regular fa-star"></i></div>
                    <div class="range-card-content">
                        <h3><span class="bold">5-20 Meters RANGE </span></h3>
                        <p>
                            Start out shooting at 10 Meters if you'd like! Our range can
                            accommodate <span class="bold">all skill levels.</span>
                        </p>
                    </div>
                </div>
                <!-- card 2 -->
                <div class="range-card">
                    <div class="range-icon">
                        <i class="fa-solid fa-crosshairs"></i>
                    </div>
                    <div class="range-card-content">
                        <h3> <span class="bold">FAMILY FRIENDLY: AGE 10+</span></h3>
                        <p>
                            Bring the whole family! A great way to spend your evenings or
                            afternoons with us at Archery
                        </p>
                    </div>
                </div>
                <!-- card 3 -->
                <div class="range-card">
                    <div class="range-icon">
                        <i class="fa-sharp fa-solid fa-credit-card"></i>
                    </div>
                    <div class="range-card-content">
                        <h3>
                            <span class="bold"> ONLY 30 GEL/HOUR</span>
                            <span class="bold">EQUIPMENT PROVIDED</span>
                        </h3>
                        <p>
                            No need to own equipment. Impact Archery will provide you with
                            the equipment and instruction.
                        </p>
                    </div>
                </div>
                <div class="range-card">
                    <div class="range-icon">
                        <i class="fa-solid fa-certificate"></i>
                    </div>
                    <div class="range-card-content">
                        <h3><span class="bold">PROFESSIONAL HELP</span></h3>
                        <p>
                            Our certified professionals will assist you while you shoot.
                        </p>
                    </div>
                </div>
            </div>
            <div class="range-right-content">
                <div class="slide-container">
                    <div class="images-container">
                        <img class="img-slide" src="./images/img2.jpg" alt="" />
                        <img class="img-slide" src="./images/img3.jpg" alt="" />
                        <img class="img-slide" src="./images/img1.jpg" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>